/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;
 import interfaz.paneles.PanelIMG;
/**
 *
 * @author Juan Felipe
 */
public class Inicio extends javax.swing.JFrame {
    PanelIMG inicioFondo = new PanelIMG();
    PanelIMG inicioMarco = new PanelIMG();
    PanelIMG howtoplay = new PanelIMG();
    PanelIMG tableInicio = new PanelIMG();
    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        this.setTitle("ArkanoidGame");
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        inicioFondo.setLayout(null);
        inicioFondo.setImage("recursos/inicioimg.jpg");
        inicioFondo.setBounds(0, 0, 1200, 675);
        this.getContentPane().add(inicioFondo);
        inicioMarco.setBounds(0, 0, 1200, 675);
        inicioMarco.setOpaque(false);
        inicioMarco.setImage("recursos/marco0.png");
        inicioMarco.setLayout(null);
        inicioFondo.add(inicioMarco);
        howtoplay.setLayout(null);
        howtoplay.setImage("recursos/slide1howtoplay.png");
        howtoplay.setBounds(470, 100, 650, 475);
        howtoplay.setOpaque(false);
        inicioFondo.add(howtoplay);       
        tableInicio.setLayout(null);
        tableInicio.setImage("recursos/tableinicio.png");
        tableInicio.setBounds(30, 30, 388, 615);
        tableInicio.setOpaque(false);
        inicioFondo.add(tableInicio);
 
        
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 675, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
