/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import componente.Bloque;
import componente.PanelComponente;
import componente.Raqueta;
import interfaz.paneles.PanelIMG;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JPanel;
import javax.swing.Timer;

/**
 *
 * @author Juan Felipe
 */
public class Juego extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    PanelIMG fondo = new PanelIMG();
    PanelIMG game = new PanelIMG();
    PanelIMG marco = new PanelIMG();

    public Juego() {
        this.setUndecorated(true);
        initComponents();
        this.setTitle("ArkanoidGame");
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        fondo.setLayout(null); // Establecer un diseño nulo para el fondo Panel
        fondo.setBounds(0, 0, 1200, 675);
        fondo.setImage("recursos/fondo3.jpg");
        this.getContentPane().add(fondo);
        game.setOpaque(false);
        game.setBounds(30, 30, 836, 615);
        game.scaleImage(840, 615);
        game.setImage("recursos/fondopartidasolido.png");
        marco.setBounds(0, 0, 1200, 675);
        marco.setOpaque(false);
        marco.setImage("recursos/marcojuego.png");
        fondo.add(marco);
        fondo.add(game);
        game.setLayout(null);
        marco.setLayout(null);
        //game.setBounds(30, 30, 110, 30);
        Raqueta r = new Raqueta(30, 525, 110, 30, game);
        game.add(r);

        this.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                int keyCode = e.getKeyCode();

                switch (keyCode) {
                    case 39:
                        r.moverDerecha();
                        break;
                    case 37:
                        r.moverIzquierda();
                        break;
                    case 68:
                        r.moverDerecha();
                        break;
                    case 65:
                        r.moverIzquierda();
                        break;
                }
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 675, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Juego.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Juego.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Juego.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Juego.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Juego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
