/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import interfaz.paneles.PanelIMG;
import java.awt.Image;
import javax.swing.*;

/**
 *
 * @author nalis
 */
public class Settings extends javax.swing.JFrame {
    
    PanelIMG settingsPanel = new PanelIMG();
    PanelIMG settingsMarco = new PanelIMG();
    PanelIMG subPanels = new PanelIMG();
    JButton acceptButton  = new JButton();
    JButton cancelButton = new JButton();
    JButton easyButton = new JButton();
    JButton normalButton = new JButton();
    JButton hardButton = new JButton();
    JButton BminusButton = new JButton();
    JButton BplusButton = new JButton();
    JButton VminusButton = new JButton();
    JButton VplusButton = new JButton();
    JLabel ballsState = new JLabel();
    JLabel volumeState = new JLabel();
    
    
    /**
     * Creates new form Settings
     */
    public Settings() {
        this.setUndecorated(true);
        initComponents();
        this.setTitle("Ocaso Arkanoid");
        this.setSize(1200, 675);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        setIconImage(new ImageIcon("recursos/logo.png").getImage());
        settingsMarco.setBounds(0, 0, 1200, 675);
        settingsMarco.setOpaque(false);
        settingsMarco.setImage("recursos/marco0.png");
        settingsMarco.setLayout(null);
        this.getContentPane().add(settingsMarco);
        settingsPanel.setImage("recursos/settingsBackPanel.png");
        settingsPanel.setBounds(30,30, 1140, 615);
        settingsPanel.setLayout(null);
        settingsPanel.setOpaque(false);
        this.getContentPane().add(settingsPanel);
        
        acceptButton.setIcon(new ImageIcon("recursos/acceptButton.png"));
        acceptButton.setRolloverIcon(new ImageIcon("recursos/acceptButtonPressed.png"));
        acceptButton.setBounds(600, 520, 220,94);
        acceptButton.setBorderPainted(false);
        acceptButton.setContentAreaFilled(false);
        acceptButton.setOpaque(false);
        acceptButton.setLayout(null);
        settingsPanel.add(acceptButton);
 
        cancelButton.setIcon(new ImageIcon("recursos/cancelButton.png"));
        cancelButton.setRolloverIcon(new ImageIcon("recursos/cancelButtonPressed.png"));
        cancelButton.setBounds(320, 522, 218,94);
        cancelButton.setBorderPainted(false);
        cancelButton.setContentAreaFilled(false);
        cancelButton.setOpaque(false);
        cancelButton.setLayout(null);
        settingsPanel.add(cancelButton);        
        
        subPanels.setImage("recursos/settingsSubPanels.png");
        subPanels.scaleImage(970, 403);
        subPanels.setBounds(80, 110, 970, 403);
        subPanels.setLayout(null);
        subPanels.setOpaque(false);
        settingsPanel.add(subPanels);
        
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Settings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
