/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import interfaz.paneles.PanelIMG;
import java.awt.event.ActionEvent;
import javax.swing.*;

public class Warning extends javax.swing.JFrame {

    private PanelIMG WarningImage = new PanelIMG();
    private JButton YesButton = new JButton();
    private JButton NoButton = new JButton();

    public boolean choice;

    public Warning() {
        setUndecorated(true);
        initComponents();
        this.setTitle("Ocaso Arkanoid");
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setSize(500, 320);
        WarningImage.setImage("recursos/warningPanel.png");
        WarningImage.setBounds(0, 0, 500, 320);
        WarningImage.setLayout(null);
        WarningImage.setOpaque(false);
        this.getContentPane().add(WarningImage);

        YesButton.setIcon(new ImageIcon("recursos/yesButton.png"));
        YesButton.setRolloverIcon(new ImageIcon("recursos/yesButtonPressed.png"));
        YesButton.setBounds(100, 220, 125, 85);
        YesButton.setBorderPainted(false);
        YesButton.setContentAreaFilled(false);
        YesButton.setOpaque(false);
        YesButton.setLayout(null);
        WarningImage.add(YesButton);

        YesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YesButtonActionPerformed(evt);
            }
        });

        NoButton.setIcon(new ImageIcon("recursos/noButton.png"));
        NoButton.setRolloverIcon(new ImageIcon("recursos/noButtonPressed.png"));
        NoButton.setBounds(285, 216, 110, 94);
        NoButton.setBorderPainted(false);
        NoButton.setContentAreaFilled(false);
        NoButton.setOpaque(false);
        NoButton.setLayout(null);
        WarningImage.add(NoButton);
        
        NoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoButtonActionPerformed(evt);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    private void YesButtonActionPerformed(ActionEvent evt) {
        choice = true;
        dispose();
    }
    private void NoButtonActionPerformed(ActionEvent evt) {
        choice = false;
        dispose();
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Warning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Warning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Warning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Warning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Warning().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
